version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskcircledb
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - type: bind
        source: ./backend/src/main/resources
        target: /docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: ./dev.Dockerfile
    env_file:
      - ./.env
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
