FROM openjdk:11-slim
COPY ../frontend /usr/src/frontend
COPY ../backend /usr/src/backend
WORKDIR /usr/src/backend
# RUN chmod +x mvnw
# RUN ./mvnw install
# RUN ./mvnw package
# ENTRYPOINT ["java","-jar","target/taskcircle-1.0.0.jar"]
